In [2]:
import sys
import os

import json
import pandas as pd
import numpy as np

_rel_path = os.path.realpath('')
base_path = os.path.abspath(_rel_path)

data_path = os.path.join(base_path, 'data')
raw_data_path = os.path.join(data_path, 'raw_data')
cleaned_data_path = os.path.join(data_path, 'cleaned_data')

In [3]:
all_rugby_matches_dict = json.load(open(os.path.join(raw_data_path, 'all_rugby_matches.json')))

In [4]:
international_teams_dict = json.load(open(os.path.join(raw_data_path, "international_rugby_team_ids.json")))

In [5]:
all_rugby_matches_df = pd.DataFrame().from_dict(all_rugby_matches_dict).T.reset_index(names=['matchId'])

print(f'Number of Total Matches: {all_rugby_matches_df.shape[0]}\n')

Number of Total Matches: 32917

In [6]:
international_rugby_matches = all_rugby_matches_df[(all_rugby_matches_df['teamAid'].isin(international_teams_dict.keys()))&(all_rugby_matches_df['teamBid'].isin(international_teams_dict.keys()))]
international_rugby_matches = international_rugby_matches.reset_index(drop=True)

print(f'Number of International Matches: {international_rugby_matches.shape[0]}\n')

international_rugby_matches.head()

Number of International Matches: 12000

,matchId,matchAltId,description,eventPhase,venueId,venueAltId,venueName,venueCity,venueCountry,matchDate,...,teamBmetadata,teamBscore,matchResult,matchKc,matchStatus,matchOutcome,events,sport,competition,venue
0,751,9460bad1-f984-49e7-a5c9-936abd59303a,None,None,10,891baf0c-8ab8-4aaa-840e-ed01a8a59c8c,Raeburn Place,Edinburgh,Scotland,1871-03-27,...,{},0,"[0, 0]",None,C,D,[],None,None,NaN
1,752,e522a55b-f305-49bb-9ee7-8217ead4061d,None,None,75,44c7a059-3e96-41f3-8af3-298972a34a3e,Kennington Oval,London,England,1872-02-05,...,{},0,"[0, 0]",None,C,D,[],None,None,NaN
2,753,ecc6e0e2-5710-4c1a-a1fe-972bd62dfb3d,None,None,16,69df3ea1-6aaf-49b7-abd2-83c266bf9685,Hamilton Crescent,Glasgow,Scotland,1873-03-03,...,{},0,"[0, 0]",None,C,D,[],None,None,NaN
3,754,7f68ec57-5b1d-496d-ba95-370bdfa98ba7,None,None,75,44c7a059-3e96-41f3-8af3-298972a34a3e,Kennington Oval,London,England,1874-02-23,...,{},0,"[0, 0]",None,C,D,[],None,None,NaN
4,755,a2d0ac5a-6f07-44cc-a306-b9a3f31f0dbe,None,None,75,44c7a059-3e96-41f3-8af3-298972a34a3e,Kennington Oval,London,England,1875-02-15,...,{},0,"[0, 0]",None,C,D,[],None,None,NaN

In [7]:
def scoring_system(row):
    scoring_system = ''
    if row['matchDate'] <= '1875-12-31':
        scoring_system = '1'
    elif row['matchDate'] >= '1876-01-01' and row['matchDate'] <= '1889-12-31':
        scoring_system = '2'
    elif row['matchDate'] >= '1890-01-01' and row['matchDate'] <= '1891-12-31':
        scoring_system = '3'
    elif row['matchDate'] >= '1892-01-01' and row['matchDate'] <= '1893-12-31':
        scoring_system = '4'
    elif row['matchDate'] >= '1894-01-01' and row['matchDate'] <= '1904-12-31':
        scoring_system = '5'
    elif row['matchDate'] >= '1905-01-01' and row['matchDate'] <= '1947-12-31':
        scoring_system = '6'
    elif row['matchDate'] >= '1948-01-01' and row['matchDate'] <= '1970-12-31':
        scoring_system = '7'
    elif row['matchDate'] >= '1971-01-01' and row['matchDate'] <= '1971-12-31':
        scoring_system = '8'
    elif row['matchDate'] >= '1972-01-01' and row['matchDate'] <= '1991-12-31':
        scoring_system = '9'
    elif row['matchDate'] >= '1992-01-01':
        scoring_system = '10'

    return scoring_system

In [8]:
international_rugby_matches['scoring_system'] = international_rugby_matches.apply(lambda x: scoring_system(x), axis=1)

In [12]:
international_rugby_matches['matchDate'] = pd.to_datetime(international_rugby_matches['matchDate'])
international_rugby_matches = international_rugby_matches.sort_values(by='matchDate').reset_index(drop=True)

international_rugby_matches.head()

,matchId,matchAltId,description,eventPhase,venueId,venueAltId,venueName,venueCity,venueCountry,matchDate,...,teamBscore,matchResult,matchKc,matchStatus,matchOutcome,events,sport,competition,venue,scoring_system
0,751,9460bad1-f984-49e7-a5c9-936abd59303a,None,None,10,891baf0c-8ab8-4aaa-840e-ed01a8a59c8c,Raeburn Place,Edinburgh,Scotland,1871-03-27,...,0,"[0, 0]",None,C,D,[],None,None,NaN,1
1,752,e522a55b-f305-49bb-9ee7-8217ead4061d,None,None,75,44c7a059-3e96-41f3-8af3-298972a34a3e,Kennington Oval,London,England,1872-02-05,...,0,"[0, 0]",None,C,D,[],None,None,NaN,1
2,753,ecc6e0e2-5710-4c1a-a1fe-972bd62dfb3d,None,None,16,69df3ea1-6aaf-49b7-abd2-83c266bf9685,Hamilton Crescent,Glasgow,Scotland,1873-03-03,...,0,"[0, 0]",None,C,D,[],None,None,NaN,1
3,754,7f68ec57-5b1d-496d-ba95-370bdfa98ba7,None,None,75,44c7a059-3e96-41f3-8af3-298972a34a3e,Kennington Oval,London,England,1874-02-23,...,0,"[0, 0]",None,C,D,[],None,None,NaN,1
4,755,a2d0ac5a-6f07-44cc-a306-b9a3f31f0dbe,None,None,75,44c7a059-3e96-41f3-8af3-298972a34a3e,Kennington Oval,London,England,1875-02-15,...,0,"[0, 0]",None,C,D,[],None,None,NaN,1

In [16]:
international_rugby_matches[international_rugby_matches['scoring_system'].isin(['1', '2'])]['scoring_system'].value_counts()

scoring_system
2    53
1     7
Name: count, dtype: int64

In [17]:
international_rugby_matches[international_rugby_matches['scoring_system'].isin(['1', '2'])]['matchResult'].value_counts()

matchResult
[0, 0]    60
Name: count, dtype: int64

In [18]:
international_rugby_matches[international_rugby_matches['scoring_system'].isin(['1'])]['competition'].value_counts(dropna=False)

competition
None    7
Name: count, dtype: int64

In [19]:
international_rugby_matches['teamAgoals'] = 0
international_rugby_matches['teamBtgoals'] = 0
international_rugby_matches['teamAtries'] = 0
international_rugby_matches['teamBtries'] = 0
international_rugby_matches['teamAconversions'] = 0
international_rugby_matches['teamBtconversions'] = 0
international_rugby_matches['teamApenalties'] = 0
international_rugby_matches['teamBtpenalties'] = 0
international_rugby_matches['teamAdropgoals'] = 0
international_rugby_matches['teamBtdropgoals'] = 0
international_rugby_matches['teamAgoals'] = 0
international_rugby_matches['teamBtgoals'] = 0
international_rugby_matches['teamAgoalsfrommark'] = 0
international_rugby_matches['teamBtgoalsfrommark'] = 0

In [87]:
international_rugby_matches[international_rugby_matches['scoring_system']=='2'][['matchId', 'matchDate', 'teamAname', 'teamBname']]

   matchId  matchDate teamAname teamBname
7      759 1876-03-06   England  Scotland
8      760 1877-02-05   England   Ireland
9     2035 1877-02-19   Ireland  Scotland
10     761 1877-03-05  Scotland   England
11     762 1878-03-04   England  Scotland
12     763 1878-03-11   Ireland   England
13    2037 1879-02-17   Ireland  Scotland
14     764 1879-03-10  Scotland   England
15     765 1879-03-24   England   Ireland
16     766 1880-01-30   Ireland   England
17    2038 1880-02-14  Scotland   Ireland
18     767 1880-02-28   England  Scotland
19     768 1881-02-05   England   Ireland
20     252 1881-02-16   England     Wales
21    2039 1881-02-19   Ireland  Scotland
22     769 1881-03-19  Scotland   England
23     253 1882-01-28   Ireland     Wales
24     770 1882-02-06   Ireland   England
25    2040 1882-02-18  Scotland   Ireland
26     771 1882-03-04   England  Scotland
27     254 1882-12-16     Wales   England
28     255 1883-01-08  Scotland     Wales
29     772 1883-02-05   England   Ireland
30    1164 1883-02-17   Ireland  Scotland
31     773 1883-03-03  Scotland   England
32     256 1884-01-05   England     Wales
33     257 1884-01-12     Wales  Scotland
34     774 1884-02-04   Ireland   England
35    1165 1884-02-16  Scotland   Ireland
36     775 1884-03-01   England  Scotland
37     258 1884-04-12     Wales   Ireland
38     259 1885-01-03     Wales   England
39     260 1885-01-10  Scotland     Wales
40     776 1885-02-07   England   Ireland
41   12308 1885-02-21   Ireland  Scotland
42    1166 1885-03-07  Scotland   Ireland
43     261 1886-01-02   England     Wales
44     262 1886-01-09     Wales  Scotland
45     777 1886-02-06   Ireland   England
46    1167 1886-02-20  Scotland   Ireland
47     778 1886-03-13  Scotland   England
48     263 1887-01-08     Wales   England
49     779 1887-02-05   Ireland   England
50    1168 1887-02-19   Ireland  Scotland
51     264 1887-02-26  Scotland     Wales
52     780 1887-03-05   England  Scotland
53     265 1887-03-12     Wales   Ireland
54     266 1888-02-04     Wales  Scotland
55     267 1888-03-03   Ireland     Wales
56    1169 1888-03-10  Scotland   Ireland
57     269 1889-02-02  Scotland     Wales
58    1170 1889-02-16   Ireland  Scotland
59     270 1889-03-02     Wales   Ireland

In [ ]:
match_id = ''

international_rugby_matches.at[international_rugby_matches.index[international_rugby_matches['matchId']==match_id][0], 'matchResult'] = [1, 0]
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAgoals'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamBtgoals'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAtries'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamBtries'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAconversions'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamBtconversions'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamApenalties'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamBtpenalties'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAdropgoals'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamBtdropgoals'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAgoals'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamBtgoals'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAgoalsfrommark'] = 0
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamBtgoalsfrommark'] = 0

In [40]:
match_id = '751'

international_rugby_matches.at[international_rugby_matches.index[international_rugby_matches['matchId']==match_id][0], 'matchResult'] = [1, 0]
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAtries'] = 2
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamBtries'] = 1
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAgoals'] = 1

In [141]:
match_id = '752'

international_rugby_matches.at[international_rugby_matches.index[international_rugby_matches['matchId']==match_id][0], 'matchResult'] = [2, 1]
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAtries'] = 2
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAgoals'] = 1
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAdropgoals'] = 1
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamBtdropgoals'] = 1

In [46]:
match_id = '754'

international_rugby_matches.at[international_rugby_matches.index[international_rugby_matches['matchId']==match_id][0], 'matchResult'] = [1, 0]
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamBtries'] = 1
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAdropgoals'] = 1

In [54]:
match_id = '755'

international_rugby_matches.at[international_rugby_matches.index[international_rugby_matches['matchId']==match_id][0], 'matchResult'] = [2, 0]
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAgoals'] = 1
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAtries'] = 1
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAdropgoals'] = 1

In [64]:
match_id = '758'

international_rugby_matches.at[international_rugby_matches.index[international_rugby_matches['matchId']==match_id][0], 'matchResult'] = [0, 1]
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamBtgoals'] = 1
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamBtries'] = 1

In [68]:
match_id = '759'

international_rugby_matches.at[international_rugby_matches.index[international_rugby_matches['matchId']==match_id][0], 'matchResult'] = [1, 0]
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAtgoals'] = 1
international_rugby_matches.loc[international_rugby_matches['matchId']==match_id, 'teamAtries'] = 1

In [72]:
match_id = '760'

international_rugby_matches.loc[international_rugby_matches['matchId']==match_id]

,matchId,matchAltId,description,eventPhase,venueId,venueAltId,venueName,venueCity,venueCountry,matchDate,...,teamBtries,teamAconversions,teamBtconversions,teamApenalties,teamBtpenalties,teamAdropgoals,teamBtdropgoals,teamAgoalsfrommark,teamBtgoalsfrommark,teamAtgoals
8,760,2974a793-8f02-4b4a-932a-b5f84463739d,None,None,75,44c7a059-3e96-41f3-8af3-298972a34a3e,Kennington Oval,London,England,1877-02-05,...,0,0,0,0,0,0,0,0,0,NaN

In [52]:
international_rugby_matches.loc[international_rugby_matches['matchId']=='755']['teamBname']

4    Ireland
Name: teamBname, dtype: object

In [36]:
international_rugby_matches[international_rugby_matches['scoring_system'].isin(['2'])]['competition'].value_counts(dropna=False)

competition
None                 21
Home Nations 1884     6
Home Nations 1887     6
Home Nations 1883     5
Home Nations 1886     5
Home Nations 1885     4
Home Nations 1888     3
Home Nations 1889     3
Name: count, dtype: int64

In [18]:
international_rugby_matches[international_rugby_matches['scoring_system'].isin(['1', '2'])].shape

(60, 36)

In [20]:
international_rugby_matches[international_rugby_matches['scoring_system'].isin(['3'])]

,matchId,matchAltId,description,eventPhase,venueId,venueAltId,venueName,venueCity,venueCountry,matchDate,...,teamBscore,matchResult,matchKc,matchStatus,matchOutcome,events,sport,competition,venue,scoring_system
60,271,fcafd1fb-214e-4b98-bd60-84b631ce88de,None,None,2,48c725b9-38ce-48f4-8fae-845dfd6eb93f,Cardiff Arms Park,Cardiff,Wales,1890-02-01,...,5,"[1, 5]",None,C,B,"[{'id': '245', 'altId': '51571718-06b7-4dbd-bd...",MRU,Home Nations 1890,NaN,3
61,272,9bb14928-fb63-44ec-94ad-67a96e2148b2,None,None,19,2cd1b364-ad52-46b0-af95-71562a2c15a0,Crown Flatt,Dewsbury,England,1890-02-15,...,1,"[0, 1]",None,C,B,"[{'id': '245', 'altId': '51571718-06b7-4dbd-bd...",MRU,Home Nations 1890,NaN,3
62,1171,ff7a5d11-8bd7-4cab-84af-3af1cd5f74b8,None,None,10,891baf0c-8ab8-4aaa-840e-ed01a8a59c8c,Raeburn Place,Edinburgh,Scotland,1890-02-22,...,0,"[5, 0]",None,C,A,"[{'id': '245', 'altId': '51571718-06b7-4dbd-bd...",MRU,Home Nations 1890,NaN,3
63,273,54e101f0-72cd-4c5b-a474-0db4b3e51281,None,None,4,f96114bb-dfc7-4da9-87d8-a694fdd6314f,Lansdowne Road,Dublin,Ireland,1890-03-01,...,0,"[0, 0]",None,C,D,"[{'id': '245', 'altId': '51571718-06b7-4dbd-bd...",MRU,Home Nations 1890,NaN,3
64,782,b7e4a866-ced5-45bf-b67c-9e7716ab1737,None,None,10,891baf0c-8ab8-4aaa-840e-ed01a8a59c8c,Raeburn Place,Edinburgh,Scotland,1890-03-01,...,6,"[0, 6]",None,C,B,"[{'id': '245', 'altId': '51571718-06b7-4dbd-bd...",MRU,Home Nations 1890,NaN,3
65,783,964da4b8-15cd-49c2-b843-2fd5de70d0e3,None,None,15,d7d93e5b-ef72-45a3-9b02-5a902cdf8871,Rectory Field,Blackheath,England,1890-03-15,...,0,"[3, 0]",None,C,A,"[{'id': '245', 'altId': '51571718-06b7-4dbd-bd...",MRU,Home Nations 1890,NaN,3
66,274,cac349b4-171f-4311-b9b0-9ba6a7c8873b,None,None,14,b960ac17-2cb5-4858-9a41-ae7d7522545c,Rodney Parade,Newport,Wales,1891-01-03,...,7,"[3, 7]",None,C,B,"[{'id': '244', 'altId': 'e981541d-7f85-48e3-8d...",MRU,Home Nations 1891,NaN,3
67,784,26389281-c528-450f-9086-4e4a51dbca34,None,None,4,f96114bb-dfc7-4da9-87d8-a694fdd6314f,Lansdowne Road,Dublin,Ireland,1891-02-07,...,9,"[0, 9]",None,C,B,"[{'id': '244', 'altId': 'e981541d-7f85-48e3-8d...",MRU,Home Nations 1891,NaN,3
68,275,22995c12-76d9-49bc-895a-5637a20b6eb2,None,None,10,891baf0c-8ab8-4aaa-840e-ed01a8a59c8c,Raeburn Place,Edinburgh,Scotland,1891-02-07,...,0,"[15, 0]",None,C,A,"[{'id': '244', 'altId': 'e981541d-7f85-48e3-8d...",MRU,Home Nations 1891,NaN,3
69,1172,f4588372-8c15-46d6-a8ac-e92506744385,None,None,20,9119e081-d435-4b9b-ae2e-eafc33db7bb7,Ballynafeigh,Belfast,Northern Ireland,1891-02-21,...,14,"[0, 14]",None,C,B,"[{'id': '244', 'altId': 'e981541d-7f85-48e3-8d...",MRU,Home Nations 1891,NaN,3
70,276,42777927-798f-4c71-8a77-2b1e5bf4fac6,None,None,17,2cb51788-f59e-46b5-930d-ca5b0c6f48c8,Stradey Park,Llanelli,Wales,1891-03-07,...,4,"[6, 4]",None,C,A,"[{'id': '244', 'altId': 'e981541d-7f85-48e3-8d...",MRU,Home Nations 1891,NaN,3
71,785,c41179d5-e178-4161-a30f-8d4dec2c3c07,None,None,21,1752eb94-ac70-4de8-81b3-89e3475f69a8,Athletic Ground,Richmond,England,1891-03-07,...,9,"[3, 9]",None,C,B,"[{'id': '244', 'altId': 'e981541d-7f85-48e3-8d...",MRU,Home Nations 1891,NaN,3

In [24]:
international_rugby_matches[international_rugby_matches['scoring_system'].isin(['4'])]['competition'].value_counts()

competition
Home Nations 1892    6
Home Nations 1893    6
Name: count, dtype: int64